
version: "3"
services:
  app:
    image: simple-wars-django
    restart: "unless-stopped"
    build:
      context: ../
      dockerfile: docker/django/Dockerfile
    depends_on:
      - db
    expose:
      - 8000
    ports:
      - "8000:8000"
    command:
      - /bin/bash
      - -c
      - |
        sleep 5
        python manage.py runserver 0.0.0.0:8000
  db:
    image: simple-wars-mysql
    restart: "unless-stopped"
    build:
      context: ../
      dockerfile: docker/db/Dockerfile
    expose:
      - 3306
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_PORT: "3306"
    volumes:
      - data:/var/lib/mysql
volumes:
  data: